version: '3.9'

services:
  api:
    # Restart on crash + start on system reboot
    restart: always
    image: ccsds_structure_manager
    build: .
    container_name: ccsds_structure_manager
    ports:
      - "8000:8000"
    env_file:
      - .env